In [12]:
! pip install numpy
! pip install pandas
%pip install numpy
%pip install pandas

import numpy as np
import pandas as pd

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [13]:
#reading the dataset
df=pd.read_csv("twitter_training.csv")

In [14]:
df.head()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...


In [15]:
%pip install nltk
import nltk

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [16]:
nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/saishivanadhula/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/saishivanadhula/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [17]:
from nltk.tokenize import word_tokenize

In [18]:
df.tail()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
74676,9200,Nvidia,Positive,Just realized that the Windows partition of my...
74677,9200,Nvidia,Positive,Just realized that my Mac window partition is ...
74678,9200,Nvidia,Positive,Just realized the windows partition of my Mac ...
74679,9200,Nvidia,Positive,Just realized between the windows partition of...
74680,9200,Nvidia,Positive,Just like the windows partition of my Mac is l...


In [19]:
x=df.iloc[0,1]
x

'Borderlands'

In [20]:
import re

In [22]:
if 'Text' in df.columns:
    df['Text'] = df['Text'].dropna()
    df['Text'] = df['Text'].astype(str)
else:
    print("Column 'Text' not found in DataFrame!")


Column 'Text' not found in DataFrame!


In [83]:
#data cleaning

# Remove special characters and punctuation using regex
mydata=[] #empty list
for i in df['Text']:
  text = re.sub(r',','',i)
  cleaned_text = re.sub(r'[^\w\s]', '', text)  # Removes everything except word characters and spaces
  cleaned_text = re.sub(r'\s+', ' ', cleaned_text)  # Replaces multiple spaces with a single space
  cleaned_data = cleaned_text.strip()  # Removes leading/trailing whitespace
  mydata.append(cleaned_data)

In [84]:
mydata

['Kickers on my watchlist XIDE TIT SOQ PNK CPW BPZ AJ trade method 1 or method 2 see prev posts',
 'user AAP MOVIE 55 return for the FEAGEED indicator just 15 trades for the year AWESOME',
 'user Id be afraid to short AMZN they are looking like a nearmonopoly in eBooks and infrastructureasaservice',
 'MNTA Over 1200',
 'OI Over 2137',
 'PGNX Over 304',
 'AAP user if so then the current downtrend will break Otherwise just a shortterm correction in medterm downtrend',
 'Mondays relative weakness NYX WIN TIE TAP ICE INT BMC AON C CHK BIIB',
 'GOOG ower trend line channel test volume support',
 'AAP will watch tomorrow for ONG entry',
 'im assuming FCX opens tomorrow above the 3425 trigger buy still very much like this setup',
 'It really worries me how everyone expects the market to rally nowusually exact opposite happens every time we shall see soon bac spx jpm',
 'AAP GAMCOs arry Haverty Apple Is Extremely Cheap Great Video',
 'user Maykiljil posted that I agree that MSFT is going highe

In [85]:
tokens=[word_tokenize(x) for x in df['Text']]

In [86]:
tokens[5]

['PGNX', 'Over', '3.04']

In [87]:
#to remove stop words
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mehna\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [88]:
stop=stopwords.words('english')

In [89]:
stop_token=[]
for x in tokens:
  cl = [i for i in x if i not in stop]
  stop_token.append(cl)

In [90]:
stop_token

[['Kickers',
  'watchlist',
  'XIDE',
  'TIT',
  'SOQ',
  'PNK',
  'CPW',
  'BPZ',
  'AJ',
  'trade',
  'method',
  '1',
  'method',
  '2',
  ',',
  'see',
  'prev',
  'posts'],
 ['user',
  ':',
  'AAP',
  'MOVIE',
  '.',
  '55',
  '%',
  'return',
  'FEA/GEED',
  'indicator',
  '15',
  'trades',
  'year',
  '.',
  'AWESOME',
  '.'],
 ['user',
  'I',
  "'d",
  'afraid',
  'short',
  'AMZN',
  '-',
  'looking',
  'like',
  'near-monopoly',
  'eBooks',
  'infrastructure-as-a-service'],
 ['MNTA', 'Over', '12.00'],
 ['OI', 'Over', '21.37'],
 ['PGNX', 'Over', '3.04'],
 ['AAP',
  '-',
  'user',
  'current',
  'downtrend',
  'break',
  '.',
  'Otherwise',
  'short-term',
  'correction',
  'med-term',
  'downtrend',
  '.'],
 ['Monday',
  "'s",
  'relative',
  'weakness',
  '.',
  'NYX',
  'WIN',
  'TIE',
  'TAP',
  'ICE',
  'INT',
  'BMC',
  'AON',
  'C',
  'CHK',
  'BIIB'],
 ['GOOG',
  '-',
  'ower',
  'trend',
  'line',
  'channel',
  'test',
  '&',
  'volume',
  'support',
  '.'],
 ['AAP', 

In [91]:
from nltk.stem import PorterStemmer
ps=PorterStemmer()

In [92]:
stemedata =[]
for message in stop_token:
  st = [ps.stem(word) for word in message]
  stemedata.append(st)

In [93]:
stemedata

[['kicker',
  'watchlist',
  'xide',
  'tit',
  'soq',
  'pnk',
  'cpw',
  'bpz',
  'aj',
  'trade',
  'method',
  '1',
  'method',
  '2',
  ',',
  'see',
  'prev',
  'post'],
 ['user',
  ':',
  'aap',
  'movi',
  '.',
  '55',
  '%',
  'return',
  'fea/ge',
  'indic',
  '15',
  'trade',
  'year',
  '.',
  'awesom',
  '.'],
 ['user',
  'i',
  "'d",
  'afraid',
  'short',
  'amzn',
  '-',
  'look',
  'like',
  'near-monopoli',
  'ebook',
  'infrastructure-as-a-servic'],
 ['mnta', 'over', '12.00'],
 ['oi', 'over', '21.37'],
 ['pgnx', 'over', '3.04'],
 ['aap',
  '-',
  'user',
  'current',
  'downtrend',
  'break',
  '.',
  'otherwis',
  'short-term',
  'correct',
  'med-term',
  'downtrend',
  '.'],
 ['monday',
  "'s",
  'rel',
  'weak',
  '.',
  'nyx',
  'win',
  'tie',
  'tap',
  'ice',
  'int',
  'bmc',
  'aon',
  'c',
  'chk',
  'biib'],
 ['goog',
  '-',
  'ower',
  'trend',
  'line',
  'channel',
  'test',
  '&',
  'volum',
  'support',
  '.'],
 ['aap', 'watch', 'tomorrow', 'ong', 'e

In [94]:
#apply pos_tagging on data
from nltk.tag import pos_tag
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\mehna\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


True

In [95]:
pos_token=[pos_tag(message) for message in stop_token]

In [96]:
pos_token

[[('Kickers', 'NNS'),
  ('watchlist', 'VBP'),
  ('XIDE', 'NNP'),
  ('TIT', 'NNP'),
  ('SOQ', 'NNP'),
  ('PNK', 'NNP'),
  ('CPW', 'NNP'),
  ('BPZ', 'NNP'),
  ('AJ', 'NNP'),
  ('trade', 'NN'),
  ('method', 'NN'),
  ('1', 'CD'),
  ('method', 'NN'),
  ('2', 'CD'),
  (',', ','),
  ('see', 'VBP'),
  ('prev', 'JJ'),
  ('posts', 'NNS')],
 [('user', 'NN'),
  (':', ':'),
  ('AAP', 'NNP'),
  ('MOVIE', 'NNP'),
  ('.', '.'),
  ('55', 'CD'),
  ('%', 'NN'),
  ('return', 'NN'),
  ('FEA/GEED', 'NNP'),
  ('indicator', 'NN'),
  ('15', 'CD'),
  ('trades', 'NNS'),
  ('year', 'NN'),
  ('.', '.'),
  ('AWESOME', 'NNP'),
  ('.', '.')],
 [('user', 'NN'),
  ('I', 'PRP'),
  ("'d", 'MD'),
  ('afraid', 'VB'),
  ('short', 'JJ'),
  ('AMZN', 'NNP'),
  ('-', ':'),
  ('looking', 'VBG'),
  ('like', 'IN'),
  ('near-monopoly', 'JJ'),
  ('eBooks', 'NNS'),
  ('infrastructure-as-a-service', 'JJ')],
 [('MNTA', 'NNP'), ('Over', 'NNP'), ('12.00', 'CD')],
 [('OI', 'NNP'), ('Over', 'NNP'), ('21.37', 'CD')],
 [('PGNX', 'NNP'), ('Ov

In [97]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('omw-1.4')
lemmatizer=WordNetLemmatizer()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\mehna\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\mehna\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [98]:
from nltk.corpus import wordnet

def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    elif treebank_tag.startswith('V'):
        return wordnet.VERB
    elif treebank_tag.startswith('N'):
        return wordnet.NOUN
    elif treebank_tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN  # Default to NOUN if POS tag is unknown


In [99]:
pos_token[0][0]

('Kickers', 'NNS')

In [100]:
get_wordnet_pos(pos_token[0][0][1])

'n'

In [101]:
lem_data = []
for x in range(len(pos_token)):
  lem = [lemmatizer.lemmatize(pos_token[x][i][0],get_wordnet_pos(pos_token[x][i][1])) for i in range(len(pos_token[x]))]
  lem_data.append(lem)

In [102]:
lem_data

[['Kickers',
  'watchlist',
  'XIDE',
  'TIT',
  'SOQ',
  'PNK',
  'CPW',
  'BPZ',
  'AJ',
  'trade',
  'method',
  '1',
  'method',
  '2',
  ',',
  'see',
  'prev',
  'post'],
 ['user',
  ':',
  'AAP',
  'MOVIE',
  '.',
  '55',
  '%',
  'return',
  'FEA/GEED',
  'indicator',
  '15',
  'trade',
  'year',
  '.',
  'AWESOME',
  '.'],
 ['user',
  'I',
  "'d",
  'afraid',
  'short',
  'AMZN',
  '-',
  'look',
  'like',
  'near-monopoly',
  'eBooks',
  'infrastructure-as-a-service'],
 ['MNTA', 'Over', '12.00'],
 ['OI', 'Over', '21.37'],
 ['PGNX', 'Over', '3.04'],
 ['AAP',
  '-',
  'user',
  'current',
  'downtrend',
  'break',
  '.',
  'Otherwise',
  'short-term',
  'correction',
  'med-term',
  'downtrend',
  '.'],
 ['Monday',
  "'s",
  'relative',
  'weakness',
  '.',
  'NYX',
  'WIN',
  'TIE',
  'TAP',
  'ICE',
  'INT',
  'BMC',
  'AON',
  'C',
  'CHK',
  'BIIB'],
 ['GOOG',
  '-',
  'ower',
  'trend',
  'line',
  'channel',
  'test',
  '&',
  'volume',
  'support',
  '.'],
 ['AAP', 'watc

In [103]:
stem_vec=[' '.join(message) for message in stemedata]

In [104]:
stem_vec

['kicker watchlist xide tit soq pnk cpw bpz aj trade method 1 method 2 , see prev post',
 'user : aap movi . 55 % return fea/ge indic 15 trade year . awesom .',
 "user i 'd afraid short amzn - look like near-monopoli ebook infrastructure-as-a-servic",
 'mnta over 12.00',
 'oi over 21.37',
 'pgnx over 3.04',
 'aap - user current downtrend break . otherwis short-term correct med-term downtrend .',
 "monday 's rel weak . nyx win tie tap ice int bmc aon c chk biib",
 'goog - ower trend line channel test & volum support .',
 'aap watch tomorrow ong entri .',
 "'m assum fcx open tomorrow 34.25 trigger buy . still much like setup .",
 'it realli worri everyon expect market ralli , usual exact opposit happen everi time shall see soon bac spx jpm',
 "aap gamco 's arri haverti : appl is extrem cheap great video ! ! !",
 'user maykiljil post . i agre msft go higher & possibl north 30',
 'momentum come back etfc broke ma200 resist solid volum friday . ong set-up',
 'ha hit 35.65 mean resum target 

In [105]:
#applying count vectorization
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [123]:
x=cv.fit(stem_vec)

In [128]:
import pickle
with open("vectorizer.pickle","wb") as mdl_file:
    pickle.dump(x,mdl_file)

    

In [107]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5791, 8180))

In [108]:
y = df['Sentiment']

In [109]:
#importing multinomialnb from sklearn(naive_bayes)
from sklearn.naive_bayes import MultinomialNB

In [110]:
mb=MultinomialNB()

In [111]:
mb.fit(x,y)

MultinomialNB()

In [126]:
import pickle
with open("model.pickle","wb") as mdl_file:
    pickle.dump(mb,mdl_file)

In [112]:
df['Text'][3]

'MNTA Over 12.00  '

In [113]:
x[3]

array([1, 0, 0, ..., 0, 0, 0], shape=(8180,))

In [114]:
mb.predict([x[2]])

array([1])

In [115]:
[mb.predict([x[i]]) for i in range(len(x))]

[array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 arra

In [116]:
# Define the mapping
label_map = {1: 'positive', -1: 'negative', 0: 'neutral'} 



In [117]:

X_test = cv.transform(df)  # Convert text to numerical features
predicted_nums = mb.predict(X_test)  # Make predictions
predicted_labels = [label_map[num] for num in predicted_nums]  # Convert to labels

print(predicted_labels)


['negative', 'positive']


In [118]:
predicted_num = mb.predict([x[3]])[0]  # Extract the scalar value

# Convert to text label
predicted_label = label_map[predicted_num]

print(predicted_label)  

positive


In [119]:
for row in x:
    predicted_num = mb.predict([row])[0]  # Predict using the entire row
    predicted_label = label_map[predicted_num]
    print(predicted_label)


positive
positive
positive
positive
positive
positive
negative
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
negative
positive
positive
positive
positive
negative
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
negative
positive
positive
positive
positive
negative
positive
p

In [120]:
mb.score(x,y)

0.869797962355379

In [121]:

z=mb.predict(x)
pd.Series(z).value_counts()

 1    3921
-1    1870
Name: count, dtype: int64